### ISSUE TITLE
Assertion `a_json_object.HasMember(a_attribute)' failed on i3.get_tree()

### ISSUE THREAD

**Issue by Whalehunter** [Iskustvo/i3-ipcpp#3]
First, I'd like to say thanks for this library, it's a blast to communicate with i3 now.

I found this error after getting random segfaults and doing some tests. It turns out mupdf doesn't use the `WM_CLASS` attribute if not executed with mupdf-x11, as found [here](https://unix.stackexchange.com/questions/495053/how-do-i-assign-wm-class-when-launching-an-application).

This leads to a fail of the assertion of having an attribute named `class` while parsing the json output. The code I'm talking about is in `i3_json_parser-utility.inl` on line **133**

    template<typename T, typename = std::enable_if_t<is_supported_v<core_type_t<T>>>>
    T get_attribute_value(const rapidjson::Value& a_json_object, const char* a_attribute)
    {
        assert(a_json_object.IsObject());

        // Handle non-existing attributes.
        if constexpr (is_optional_v<T>)
        {
            if (!a_json_object.HasMember(a_attribute) || a_json_object[a_attribute].IsNull())
            {
                return std::nullopt;
            }
        }
        else
        {
            assert(a_json_object.HasMember(a_attribute));
        }

The workaround is straightforward, so now I execute `mupdf-x11` by default, but I think this exception shouldn't crash the program.

Thanks for the time.

**Comment by Iskustvo** [comment]
Thank you for your support and for taking the time to report this issue!

I have installed `mupdf-gl` to test this issue and it looks like there are neither `class` nor `instance` fields in the JSON response from `i3`.
This is everything received for `window_properties` attribute:
> "window_properties":{"title":"MuPDF: Open document","transient_for":null}

You are absolutely correct, this should not segfault since this is neither the `i3`'s issue nor miscommunication between `i3` and `i3-ipc++`, just bad assumption on my part.

Regarding the solution, I will make both `class` and `instance` fields optional in `i3-ipc++` and try to update `i3`'s documentation to clarify that all X11 window properties are optional.

**Comment by Iskustvo** [comment]
@Whalehunter, I have pushed the fix on `master` branch and will now close this issue.

Once again, thanks for raising my attention to this issue!
